## --------------Don't change the line below------------------ ##
# For more information on the different variables, and others you
# may define, see ${SOFT_DIR}/Makefile.skel and/or read the doc
include ${SOFT_WORKDIR}/env/compilation/compilevars.mk

LOCAL_NAME := platform/edrv/tsd/rda1203_gallite

LOCAL_API_DEPENDS ?= platform \
                     platform/chip/hal \
                     platform/chip/defs \
                     platform/edrv/tsd \
                     platform/edrv \
                     target \
                     platform/base/sx \
                     platform/edrv/pmd \

C_SRC := tsd.c
S_SRC :=


## --------------Don't change the line below------------------ ##
include ${SOFT_WORKDIR}/env/compilation/compilerules.mk
