/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"
#include "chip_id.h"

#include "csw_map.h"
#include "hal_map_engine.h"

// =============================================================================
//  MACROS
// =============================================================================

#define CSW_VERSION_STRING  "service_01.02.04_20091221_221"
#include "servicep_version.h"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================

// =============================================================================
// g_cswMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T HAL_MAP_VER_LOC g_cswMapVersion = SERVICE_VERSION_STRUCT;



// =============================================================================
// g_cswMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED CSW_MAP_ACCESS_T HAL_MAP_ACCESS_LOC g_cswMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// csw_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID csw_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_CSW, &g_cswMapVersion, &g_cswMapAccess);
}


