#!/bin/sh

# Remove recursively all the header files and xmd files generated by
# AUTO_XMD2H and AUTO_GEN_REVISION.
#
# Caution, if you have files that are named *_map.h or *_version.h and
# that have been changed, you will loose the modifications.

echo "Removing all *_map.h, *_version.h and *_version.xmd files..."
find . -name "*_map.h" -exec mv {} {}.old \;
find . -name "*_version.h" -exec mv {} {}.old \;
find . -name "*_version.xmd" -exec mv {} {}.old \;
svn up
echo "Done."

# To remove the generated files, type:
#find . -name "*.old" -delete
