/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"

#include "hal_map_engine.h"

#include "memd_map.h"
#include "memd_m.h"
#include "calib_m.h"



// =============================================================================
//  MACROS
// =============================================================================

#ifdef MEMD_USE_ROMULATOR
#define MEMD_VERSION_STRING "MEMD for Romulator " STRINGIFY_VALUE(ROMU_VER) " emulating " STRINGIFY_VALUE(MEMD_FLSH_MODEL)
#else
#define MEMD_VERSION_STRING "MEMD for " STRINGIFY_VALUE(MEMD_FLSH_MODEL)
#endif

// version 0: MEMD_MAP_ACCESS_T is empty
// version 1: USER_DATA_BASE and USER_DATA_SIZE are missed

#define MEMD_VERSION_NUMBER 2

#include "memdp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_memdMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED CONST HAL_MAP_VERSION_T HAL_MAP_VER_CONST_LOC g_memdMapVersion = MEMD_VERSION_STRUCT;



// =============================================================================
// g_memdMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
extern MEMD_FLASH_LAYOUT_T g_memdFlashLayout;
PROTECTED CONST MEMD_MAP_ACCESS_T HAL_MAP_ACCESS_CONST_LOC g_memdMapAccess =
{
    .ramPhySize = RAM_PHY_SIZE,
    .calibBase = CALIB_BASE,
    .calibSize = FACT_SETTINGS_BASE - CALIB_BASE,
    .calibRfBase = CALIB_BASE + offsetof(CALIB_BUFFER_T, versionTag),
    .factBase = FACT_SETTINGS_BASE,
    .factSize = FLASH_SIZE - FACT_SETTINGS_BASE,
    .flashLayout = &g_memdFlashLayout,
    .flashSize = FLASH_SIZE,
    .userBase = USER_DATA_BASE,
    .userSize = USER_DATA_SIZE
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// memd_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID memd_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_MEMD, &g_memdMapVersion, &g_memdMapAccess);
}
