/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/

#include "at.h"
#include "at_sa.h"
#include "at_utils.h"

#define FSM_POWER_DOWN_CMD_ENABLE   0x00000001
#define FSM_NORMAL_CMD_ENABLE       0x00000002
#define FSM_CHGR_NORMAL_CMD_ENABLE  0x00000004
#define FSM_CHGR_ONLY_CMD_ENABLE    0x00000008
#define FSM_ALARM_NORMAL_CMD_ENABLE 0x00000010
#define FSM_ALARM_ONLY_CMD_ENABLE   0x00000020
#define FSM_SLEEP_CMD_ENABLE        0x00000040
#define FSM_CFW_OFF_CMD_ENABLE      0x00000080

#define FSM_FULL_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)        \
                                    |(FSM_CHGR_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)        \
                                    |(FSM_ALARM_NORMAL_CMD_ENABLE)|(FSM_ALARM_ONLY_CMD_ENABLE)      \
                                    |(FSM_SLEEP_CMD_ENABLE)|(FSM_CFW_OFF_CMD_ENABLE))

#define FSM_LIMITED1_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)     \
                                        |(FSM_ALARM_ONLY_CMD_ENABLE))

#define FSM_LIMITED2_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)        \
                                        |(FSM_CHGR_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)        \
                                        |(FSM_ALARM_NORMAL_CMD_ENABLE)|(FSM_ALARM_ONLY_CMD_ENABLE)      \
                                        |(FSM_SLEEP_CMD_ENABLE)|(FSM_CFW_OFF_CMD_ENABLE))

#define FSM_DISABLE_STATUS_CMD_ENABLE   (0x00000000)

#define AT_PROC_MODE_CMD_ENABLE 0x00000001
#define AT_PROC_MODE_OLCMD_ENABLE   0x00000002
#define AT_PROC_MODE_CS_ENABLE  0x00000004
#define AT_PROC_MODE_PS_ENABLE  0x00000008

// [[Hameina[mod] 2008-4-21: can't input at, <cr>in online command state
#define AT_AT_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_FA_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CR_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// ]]Hameina[mod] 2008-4-21: can't input at, <cr>in online command state

#define AT_REPEAT_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_ATD_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATH_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// [[changyg[mod] 2008-4-29 :CS MODE ENABLE
#define AT_ATA_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLCC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTS_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CHUP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTD_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CHLD_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DLST_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTSEX_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CMGS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCA_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SMGO_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSDH_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSMP_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNMA_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCB_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMSS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// #define AT_CACM_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CSAS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRES_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_COPS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSQ_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ECSQ_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COPN_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CREG_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CPOL_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// frank add start
#ifdef AT_USER_DBS
#define AT_POSI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGSN_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#endif
// frank add start

#define AT_CCWA_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCFC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLIP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLIR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COLP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COLR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CUSD_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSSN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CACM_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CAOC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPUC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSVM_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// add by lijingyu
#define AT_CMUX_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CFGINIT_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CFGGET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_BTSET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WIFISET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_CPBS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_WPCS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNUM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_STGI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STA_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STNR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CGMM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMM_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGMR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMI_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#ifndef AT_USER_DBS
#define AT_CGSN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#endif
#define AT_GSN_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATI_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CIMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SIM_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPIN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPIN2_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPINC_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLCK_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPWD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRSM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CAMM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SIMIF_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SVRADDR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DATACLASS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CONNECT_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CMER_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CEER_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMEE_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CFUN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCLK_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATE_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATV_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATQ_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATZ_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CALA_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CALD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ANDF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATX_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// #define AT_CALD_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_ANDW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S0_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S5_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S3_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S4_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CDTMF_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_IPR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ICF_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_IFC_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_MONI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCED_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONIEND_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONPEND_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SCID_PERM        {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCID_PERM        {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SBBI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_NBBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_NBBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DPBK_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DREG_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DFFS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DSMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_PRDU_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_AUST_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_AUEND_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SAIC_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBC_PERM     {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBCE_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBCM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SCTM_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPAS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CIND_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLVL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMUT_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VGR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VGT_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRMP_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CAUDIO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SNFS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SLCD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STCD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

// ADD by wulc
#define AT_CRSL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// CPOF == SMSO  JYK 08/04/08
#define AT_CPOF_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CGDCONT_PERM         {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGDSCONT_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGTFT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGQREQ_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGQMIN_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGATT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGACT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGPADDR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGDATA_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGAUTO_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGANS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGCLASS_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGEREP_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGREG_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGSMS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CRC_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGCID_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_TCPIP_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

// #define AT_ATO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_OLCMD_ENABLE}
/*BUG /wulc/2012.02.15/because AT_PROC_MODE_OLCMD_ENABLE cause cmdline parser error*/
#define AT_ATO_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_3PLUS_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}



#define AT_MIC_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_SPEAKER_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_RECEIVER_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_HEADSET_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_ADGF_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#include "at_command_table.gperf.h"

const SA_COMMAND_TABLE_T *at_GetCmdDescriptor(const uint8_t *name, unsigned len)
{
    ATCMDLOGS(D, TSM(0), "AT CMD search %s (%d)", name, len);
    if (len <= MAX_WORD_LENGTH &&len >= MIN_WORD_LENGTH)
    {
        unsigned key = at_CommandHash(name, len);
        if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
            unsigned index = g_AtCommandHashIndex[key];
            if (index < TOTAL_KEYWORDS)
            {
                int cmp = AT_StrCaselessCmp(name, g_AtCommandTable[index].pName);
                ATCMDLOG(D, "AT CMD found key=%d index=%d cmp=%d", key, index, cmp);
                return (cmp == 0)? &g_AtCommandTable[index] : NULL;
            }
        }
    }
    return NULL;
}
