/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"
#include "chip_id.h"

#include "hal_map.h"
#include "halp_sys.h"
#include "halp_lps.h"
#include "halp_speech.h"
#include "halp_gdb_stub.h"

#include "hal_map_engine.h"



// =============================================================================
//  MACROS
// =============================================================================

// HAL_VERSION_NUMBER is defined in hal_map.xmd/h
#define HAL_VERSION_STRING "HAL for " STRINGIFY_VALUE(HAL_ASIC_CAPD) \
                           " in " STRINGIFY_VALUE(HAL_RELEASE_MODE)
#include "halp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================

extern UINT32 g_halLpsForceNoSleep;
extern HAL_GDB_SWITCH_CTX_T g_halGdbSwitchCtx;
extern UINT32 g_halTraceSwitchPortCmd;


// =============================================================================
// g_halMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T HAL_MAP_VER_LOC g_halMapVersion = HAL_VERSION_STRUCT;



// =============================================================================
// g_halMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED HAL_MAP_ACCESS_T HAL_UNCACHED_DATA_INTERNAL g_halMapAccess =
{
    .sys =
    {
        .halSysSystemFreq = (UINT32*)(UINT32)&g_halSysSystemFreq,
        .halSysLpsLock = &g_halSysLpsLock,
        .halSysFreqScalRegistry = NULL,
    },
    .lpsCtx = (HAL_LPS_CONTEXT_2_T*)&g_halLpsCtx,
    .lpsForceNoSleepPtr = &g_halLpsForceNoSleep,
    .halSpeechFifo = &g_halSpeechFifo,
    .profileControl = {
        .config = 0,
    },
    .keypadPulseHandler = NULL,
    .gdbSwitchCtxPtr = NULL,
    .gdbEnabledPtr = NULL,
    .traceSwitchPtr = &g_halTraceSwitchPortCmd,
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// hal_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID hal_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_HAL, &g_halMapVersion, &g_halMapAccess);
}
