/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"

#include "hal_map_engine.h"

#include "vois_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#define VOIS_VERSION_STRING "Hello, I'm VOIS!"
#include "voisp_version.h"
#include "voisp_map.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_voisMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T HAL_MAP_VER_LOC g_voisMapVersion = VOIS_VERSION_STRUCT;



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// vois_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID vois_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_VOIS, &g_voisMapVersion, &g_voisCtx);
}
