/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#ifndef _VOISP_MAP_H_
#define _VOISP_MAP_H_

#include "cs_types.h"

#include "voisp_version.h"
#include "vois_map.h"

#include "hal_map_engine.h"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_voisMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
EXPORT PROTECTED HAL_MAP_VERSION_T HAL_MAP_VER_LOC g_voisMapVersion;



// =============================================================================
// g_voisCtx
// -----------------------------------------------------------------------------
/// VoiS context, holding global variables, to be watched through CoolWatcher.
// =============================================================================
EXPORT PROTECTED VOIS_CONTEXT_T HAL_MAP_ACCESS_LOC g_voisCtx;



#endif // _VOISP_MAP_

