/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"

#include "hal_map_engine.h"

#include "rf_names.h"
#include "rfd_xcv.h"
#include "rfd_pa.h"
#include "rfd_sw.h"
#include "rfd_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#define RFD_VERSION_STRING "RFD for transceiver " STRINGIFY_VALUE(RFD_XCV_MODEL) \
    ", for PA " STRINGIFY_VALUE(RFD_PA_MODEL) \
    " and for switch " STRINGIFY_VALUE(RFD_SW_MODEL)
#include "rfdp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_rfdMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_rfdMapVersion = RFD_VERSION_STRUCT;



// =============================================================================
// g_rfdMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED RFD_MAP_ACCESS_T HAL_MAP_ACCESS_LOC g_rfdMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// rfd_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID rfd_RegisterYourself(VOID)
{
    // Put transceiver name (ID) in the field "number" of the version.
    g_rfdMapVersion.number = rfd_XcvCalibGetDefault()->palcust.name;

    hal_MapEngineRegisterModule(HAL_MAP_ID_RFD, (CONST HAL_MAP_VERSION_T *)&g_rfdMapVersion, &g_rfdMapAccess);
}

