/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/

#include <fs/sf_api.h>
#include <spiffs.h>

#undef SF_JOIN
#undef SF_JOIN_AGAIN
#undef SF_STATIC_ASSERT
#undef SF_SIZEOF_MEMBER
#undef SF_SPIFFS_CHECK

#define SF_JOIN_(X, Y) X##Y
#define SF_JOIN(X, Y) SF_JOIN_(X, Y)

#define SF_STATIC_ASSERT(b) \
    typedef char SF_JOIN(__sf_assert_at_line_, __LINE__)[(b) ? 0 : -1]

#define SF_SIZEOF_MEMBER(tp, mem) sizeof(((tp *)0)->mem)

#define SF_SPIFFS_CHECK(chk) SF_STATIC_ASSERT(SF_JOIN(SF_, chk) == SF_JOIN(SPIFFS_, chk))

SF_STATIC_ASSERT(sizeof(sf_file) == sizeof(spiffs_file));
SF_STATIC_ASSERT(sizeof(sf_flags) == sizeof(spiffs_flags));
SF_STATIC_ASSERT(SF_SIZEOF_MEMBER(struct sf_stat, size) == SF_SIZEOF_MEMBER(spiffs_stat, size));
SF_STATIC_ASSERT(SF_SIZEOF_MEMBER(struct sf_stat, name) == SF_SIZEOF_MEMBER(spiffs_stat, name));

// flags
SF_SPIFFS_CHECK(APPEND);
SF_SPIFFS_CHECK(TRUNC);
SF_SPIFFS_CHECK(CREAT);
SF_SPIFFS_CHECK(RDONLY);
SF_SPIFFS_CHECK(WRONLY);
SF_SPIFFS_CHECK(RDWR);
SF_SPIFFS_CHECK(DIRECT);
SF_SPIFFS_CHECK(EXCL);

// seek
SF_SPIFFS_CHECK(SEEK_SET);
SF_SPIFFS_CHECK(SEEK_CUR);
SF_SPIFFS_CHECK(SEEK_END);

// error code
SF_SPIFFS_CHECK(OK);
SF_SPIFFS_CHECK(ERR_NOT_MOUNTED);
SF_SPIFFS_CHECK(ERR_FULL);
SF_SPIFFS_CHECK(ERR_NOT_FOUND);
SF_SPIFFS_CHECK(ERR_END_OF_OBJECT);
SF_SPIFFS_CHECK(ERR_DELETED);
SF_SPIFFS_CHECK(ERR_NOT_FINALIZED);
SF_SPIFFS_CHECK(ERR_NOT_INDEX);
SF_SPIFFS_CHECK(ERR_OUT_OF_FILE_DESCS);
SF_SPIFFS_CHECK(ERR_FILE_CLOSED);
SF_SPIFFS_CHECK(ERR_FILE_DELETED);
SF_SPIFFS_CHECK(ERR_BAD_DESCRIPTOR);
SF_SPIFFS_CHECK(ERR_IS_INDEX);
SF_SPIFFS_CHECK(ERR_IS_FREE);
SF_SPIFFS_CHECK(ERR_INDEX_SPAN_MISMATCH);
SF_SPIFFS_CHECK(ERR_DATA_SPAN_MISMATCH);
SF_SPIFFS_CHECK(ERR_INDEX_REF_FREE);
SF_SPIFFS_CHECK(ERR_INDEX_REF_LU);
SF_SPIFFS_CHECK(ERR_INDEX_REF_INVALID);
SF_SPIFFS_CHECK(ERR_INDEX_FREE);
SF_SPIFFS_CHECK(ERR_INDEX_LU);
SF_SPIFFS_CHECK(ERR_INDEX_INVALID);
SF_SPIFFS_CHECK(ERR_NOT_WRITABLE);
SF_SPIFFS_CHECK(ERR_NOT_READABLE);
SF_SPIFFS_CHECK(ERR_CONFLICTING_NAME);
SF_SPIFFS_CHECK(ERR_NOT_CONFIGURED);
SF_SPIFFS_CHECK(ERR_NOT_A_FS);
SF_SPIFFS_CHECK(ERR_MOUNTED);
SF_SPIFFS_CHECK(ERR_ERASE_FAIL);
SF_SPIFFS_CHECK(ERR_MAGIC_NOT_POSSIBLE);
SF_SPIFFS_CHECK(ERR_NO_DELETED_BLOCKS);
SF_SPIFFS_CHECK(ERR_FILE_EXISTS);
SF_SPIFFS_CHECK(ERR_NOT_A_FILE);
SF_SPIFFS_CHECK(ERR_RO_NOT_IMPL);
SF_SPIFFS_CHECK(ERR_RO_ABORTED_OPERATION);
SF_SPIFFS_CHECK(ERR_PROBE_TOO_FEW_BLOCKS);
SF_SPIFFS_CHECK(ERR_PROBE_NOT_A_FS);
SF_SPIFFS_CHECK(ERR_NAME_TOO_LONG);
SF_SPIFFS_CHECK(ERR_IX_MAP_UNMAPPED);
SF_SPIFFS_CHECK(ERR_IX_MAP_MAPPED);
SF_SPIFFS_CHECK(ERR_IX_MAP_BAD_RANGE);
SF_SPIFFS_CHECK(ERR_SEEK_BOUNDS);
SF_SPIFFS_CHECK(ERR_WRONG_PARAMETER);
SF_SPIFFS_CHECK(ERR_INTERNAL);
SF_SPIFFS_CHECK(ERR_TEST);
