/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"
#include "chip_id.h"

#include "hal_map_engine.h"

#include "sx_map.h"


// =============================================================================
//  MACROS
// =============================================================================

#define SX_VERSION_STRING "Hello, I'm SX!"
#include "sxp_version.h"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================

extern UINT32 g_sxsDebugIdleHookEnable;

// =============================================================================
// g_sxMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T HAL_MAP_VER_LOC g_sxMapVersion = SX_VERSION_STRUCT;

// =============================================================================
// g_sxMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
extern void sxr_Task;
extern void sxr_Sbx;
extern void sxr_Mutex;
extern UINT32 sxr_Heap[];
extern UINT32 sxr_Cluster[];
extern UINT32 sxr_UsrCluster[];
PROTECTED SX_MAP_ACCESS_T HAL_MAP_ACCESS_LOC g_sxMapAccess =
{
    // Put your initialization here.
    .sxExternalTraceEnablePtr = NULL,
    .sxsDebugIdleHookEnablePtr = (UINT32*)&g_sxsDebugIdleHookEnable,
    .sxrTaskPtr = (UINT32*)&sxr_Task,
    .sxrSbxPtr = (UINT32*)&sxr_Sbx,
    .sxrMutexPtr = (UINT32*)&sxr_Mutex,
    .sxrHeapPtr = (UINT32*)sxr_Heap,
    .sxrClusterPtr = (UINT32*)sxr_Cluster,
    .sxrUsrClusterPtr = (UINT32*)sxr_UsrCluster
};


// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// sx_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID sx_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_SX, &g_sxMapVersion, &g_sxMapAccess);
}

