/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"
#include "chip_id.h"

#include "at_map.h"
#include "hal_map_engine.h"

// =============================================================================
//  MACROS
// =============================================================================

#define AT_VERSION_STRING   "Hello, I'm AT!"
#include "atp_version.h"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================

// =============================================================================
// g_atMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T HAL_MAP_VER_LOC g_atMapVersion = AT_VERSION_STRUCT;



// =============================================================================
// g_atMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED AT_MAP_ACCESS_T HAL_MAP_ACCESS_LOC g_atMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// at_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the module get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID at_RegisterYourself(VOID)
{
#ifdef CHIP_HAS_AP
    hal_MapEngineRegisterModule(HAL_MAP_ID_AT, &g_atMapVersion, &g_atMapAccess);
#endif
}


