// **************************************************************************
// Generated automatically by Codegenix(TM) - (c) 2000-2004 Dafocus
// EnDec version 1.0.75
// GENERATOR: ed-multifile
// http://www.Dafocus.it/
// **************************************************************************
// REVISION HISTORY:
// DMX | 20070330 | add EGPRS_START_RADIO_BLOCK_LOOPBACK_CMD foe EDGE
// **************************************************************************
#ifndef __mm_edcf_h
#define __mm_edcf_h

#define mm_USES_MSGSET_CSN1EnDataTypes
#define mm_USES_MSGSET_mmUl
#define mm_USES_MSGSET_mmDl
#define mm_USES_MSGSET_UserDefinedDataTypes
#define mm_USES_MSGSET_SubFields
#define mm_ENUM_TDchD_Type

#define mm_UNION_TDchD_Type

#define mm_ENUM_TmmUl_Type\
	,ID_mmUl_ATTACH_REQUEST,\
	ID_mmUl_DETACH_REQUEST_MO,\
	ID_mmUl_AUTHENTICATION_AND_CIPHERING_RESPONSE,\
	ID_mmUl_PIDENTITY_RESPONSE,\
	ID_mmUl_RAU_REQUEST,\
	ID_mmUl_RAU_COMPLETE,\
	ID_mmUl_AUTHENTICATION_RESPONSE,\
    ID_mmUl_AUTHENTICATION_FAILURE,\
	ID_mmUl_CM_REESTABLISHMENT_REQUEST,\
	ID_mmUl_CM_SERVICE_ABORT,\
	ID_mmUl_CM_SERVICE_REQUEST,\
	ID_mmUl_IDENTITY_RESPONSE,\
	ID_mmUl_IMSI_DETACH_INDICATION,\
	ID_mmUl_LOCATION_UPDATE_REQUEST,\
	ID_mmUl_TMSI_REALLOCATION_COMPLETE,\
	ID_mmUl_PAGING_RESPONSE

#define mm_UNION_TmmUl_Type\
		c_ATTACH_REQUEST fld_c_ATTACH_REQUEST;\
		c_DETACH_REQUEST_MO fld_c_DETACH_REQUEST_MO;\
		c_AUTHENTICATION_AND_CIPHERING_RESPONSE fld_c_AUTHENTICATION_AND_CIPHERING_RESPONSE;\
		c_PIDENTITY_RESPONSE fld_c_PIDENTITY_RESPONSE;\
		c_RAU_REQUEST fld_c_RAU_REQUEST;\
		c_RAU_COMPLETE fld_c_RAU_COMPLETE;\
		c_AUTHENTICATION_RESPONSE fld_c_AUTHENTICATION_RESPONSE;\
		c_AUTHENTICATION_FAILURE fld_c_AUTHENTICATION_FAILURE;\
		c_CM_REESTABLISHMENT_REQUEST fld_c_CM_REESTABLISHMENT_REQUEST;\
		c_CM_SERVICE_ABORT fld_c_CM_SERVICE_ABORT;\
		c_CM_SERVICE_REQUEST fld_c_CM_SERVICE_REQUEST;\
		c_IDENTITY_RESPONSE fld_c_IDENTITY_RESPONSE;\
		c_IMSI_DETACH_INDICATION fld_c_IMSI_DETACH_INDICATION;\
		c_LOCATION_UPDATE_REQUEST fld_c_LOCATION_UPDATE_REQUEST;\
		c_TMSI_REALLOCATION_COMPLETE fld_c_TMSI_REALLOCATION_COMPLETE;\
		c_PAGING_RESPONSE fld_c_PAGING_RESPONSE;

#ifndef __EGPRS__
#define mm_ENUM_TmmDl_Type\
	,ID_mmDl_ATTACH_ACCEPT,\
	ID_mmDl_ATTACH_REJECT,\
	ID_mmDl_DETACH_REQUEST_MT,\
	ID_mmDl_DETACH_ACCEPT,\
	ID_mmDl_PTMSI_REALLOCATION_COMMAND,\
	ID_mmDl_AUTHENTICATION_AND_CIPHERING_REQUEST,\
	ID_mmDl_AUTHENTICATION_AND_CIPHERING_REJECT,\
	ID_mmDl_PIDENTITY_REQUEST,\
	ID_mmDl_RAU_ACCEPT,\
	ID_mmDl_RAU_REJECT,\
	ID_mmDl_PSTATUS,\
	ID_mmDl_GMM_INFORMATION,\
	ID_mmDl_GPRS_TEST_MODE_CMD,\
	ID_mmDl_AUTHENTICATION_REJECT,\
	ID_mmDl_AUTHENTICATION_REQUEST,\
	ID_mmDl_CM_SERVICE_ACCEPT,\
	ID_mmDl_CM_SERVICE_REJECT,\
	ID_mmDl_ABORT,\
	ID_mmDl_IDENTITY_REQUEST,\
	ID_mmDl_LOCATION_UPDATE_ACCEPT,\
	ID_mmDl_LOCATION_UPDATE_REJECT,\
	ID_mmDl_MM_INFORMATION,\
	ID_mmDl_TMSI_REALLOCATION_COMMAND

#define mm_UNION_TmmDl_Type\
		c_ATTACH_ACCEPT fld_c_ATTACH_ACCEPT;\
		c_ATTACH_REJECT fld_c_ATTACH_REJECT;\
		c_DETACH_REQUEST_MT fld_c_DETACH_REQUEST_MT;\
		c_DETACH_ACCEPT fld_c_DETACH_ACCEPT;\
		c_PTMSI_REALLOCATION_COMMAND fld_c_PTMSI_REALLOCATION_COMMAND;\
		c_AUTHENTICATION_AND_CIPHERING_REQUEST fld_c_AUTHENTICATION_AND_CIPHERING_REQUEST;\
		c_AUTHENTICATION_AND_CIPHERING_REJECT fld_c_AUTHENTICATION_AND_CIPHERING_REJECT;\
		c_PIDENTITY_REQUEST fld_c_PIDENTITY_REQUEST;\
		c_RAU_ACCEPT fld_c_RAU_ACCEPT;\
		c_RAU_REJECT fld_c_RAU_REJECT;\
		c_PSTATUS fld_c_PSTATUS;\
		c_GMM_INFORMATION fld_c_GMM_INFORMATION;\
		c_GPRS_TEST_MODE_CMD fld_c_GPRS_TEST_MODE_CMD;\
		c_AUTHENTICATION_REJECT fld_c_AUTHENTICATION_REJECT;\
		c_AUTHENTICATION_REQUEST fld_c_AUTHENTICATION_REQUEST;\
		c_CM_SERVICE_ACCEPT fld_c_CM_SERVICE_ACCEPT;\
		c_CM_SERVICE_REJECT fld_c_CM_SERVICE_REJECT;\
		c_ABORT fld_c_ABORT;\
		c_IDENTITY_REQUEST fld_c_IDENTITY_REQUEST;\
		c_LOCATION_UPDATE_ACCEPT fld_c_LOCATION_UPDATE_ACCEPT;\
		c_LOCATION_UPDATE_REJECT fld_c_LOCATION_UPDATE_REJECT;\
		c_MM_INFORMATION fld_c_MM_INFORMATION;\
		c_TMSI_REALLOCATION_COMMAND fld_c_TMSI_REALLOCATION_COMMAND;

#else
#define mm_ENUM_TmmDl_Type\
	,ID_mmDl_ATTACH_ACCEPT,\
	ID_mmDl_ATTACH_REJECT,\
	ID_mmDl_DETACH_REQUEST_MT,\
	ID_mmDl_DETACH_ACCEPT,\
	ID_mmDl_PTMSI_REALLOCATION_COMMAND,\
	ID_mmDl_AUTHENTICATION_AND_CIPHERING_REQUEST,\
	ID_mmDl_AUTHENTICATION_AND_CIPHERING_REJECT,\
	ID_mmDl_PIDENTITY_REQUEST,\
	ID_mmDl_RAU_ACCEPT,\
	ID_mmDl_RAU_REJECT,\
	ID_mmDl_PSTATUS,\
	ID_mmDl_GMM_INFORMATION,\
	ID_mmDl_GPRS_TEST_MODE_CMD,\
	ID_mmDl_AUTHENTICATION_REJECT,\
	ID_mmDl_AUTHENTICATION_REQUEST,\
	ID_mmDl_CM_SERVICE_ACCEPT,\
	ID_mmDl_CM_SERVICE_REJECT,\
	ID_mmDl_ABORT,\
	ID_mmDl_IDENTITY_REQUEST,\
	ID_mmDl_LOCATION_UPDATE_ACCEPT,\
	ID_mmDl_LOCATION_UPDATE_REJECT,\
	ID_mmDl_MM_INFORMATION,\
  ID_mmDl_TMSI_REALLOCATION_COMMAND,\
  ID_mmDl_EGPRS_START_RADIO_BLOCK_LOOPBACK_CMD



#define mm_UNION_TmmDl_Type\
		c_ATTACH_ACCEPT fld_c_ATTACH_ACCEPT;\
		c_ATTACH_REJECT fld_c_ATTACH_REJECT;\
		c_DETACH_REQUEST_MT fld_c_DETACH_REQUEST_MT;\
		c_DETACH_ACCEPT fld_c_DETACH_ACCEPT;\
		c_PTMSI_REALLOCATION_COMMAND fld_c_PTMSI_REALLOCATION_COMMAND;\
		c_AUTHENTICATION_AND_CIPHERING_REQUEST fld_c_AUTHENTICATION_AND_CIPHERING_REQUEST;\
		c_AUTHENTICATION_AND_CIPHERING_REJECT fld_c_AUTHENTICATION_AND_CIPHERING_REJECT;  \
		c_PIDENTITY_REQUEST fld_c_PIDENTITY_REQUEST;\
		c_RAU_ACCEPT fld_c_RAU_ACCEPT;\
		c_RAU_REJECT fld_c_RAU_REJECT;\
		c_PSTATUS fld_c_PSTATUS;\
		c_GMM_INFORMATION fld_c_GMM_INFORMATION;\
		c_GPRS_TEST_MODE_CMD fld_c_GPRS_TEST_MODE_CMD;\
		c_AUTHENTICATION_REJECT fld_c_AUTHENTICATION_REJECT;\
		c_AUTHENTICATION_REQUEST fld_c_AUTHENTICATION_REQUEST;\
		c_CM_SERVICE_ACCEPT fld_c_CM_SERVICE_ACCEPT;\
		c_CM_SERVICE_REJECT fld_c_CM_SERVICE_REJECT;\
		c_ABORT fld_c_ABORT;\
		c_IDENTITY_REQUEST fld_c_IDENTITY_REQUEST;\
		c_LOCATION_UPDATE_ACCEPT fld_c_LOCATION_UPDATE_ACCEPT;\
		c_LOCATION_UPDATE_REJECT fld_c_LOCATION_UPDATE_REJECT;\
		c_MM_INFORMATION fld_c_MM_INFORMATION;\
		c_TMSI_REALLOCATION_COMMAND fld_c_TMSI_REALLOCATION_COMMAND;\
		c_EGPRS_START_RADIO_BLOCK_LOOPBACK_CMD fld_c_EGPRS_START_RADIO_BLOCK_LOOPBACK_CMD;\

#endif

  
#define mm_ENUM_TccUl_Type

#define mm_UNION_TccUl_Type

#define mm_ENUM_TccDl_Type

#define mm_UNION_TccDl_Type

#define mm_ENUM_TCcch_Type

#define mm_UNION_TCcch_Type


#endif

