## --------------Don't change the line below------------------ ##
# For more information on the different variables, and others you
# may define, see ${SOFT_WORKDIR}/Makefile.skel and/or read the doc
include ${SOFT_WORKDIR}/env/compilation/compilevars.mk

LOCAL_NAME := platform/edrv/rfd/pasw_rda6231

LOCAL_API_DEPENDS := platform \
                     platform/base/common \
                     platform/chip/hal \
                     platform/chip/defs \
                     platform/edrv \
                     platform/edrv/rfd \
                     ${PLATFORM_SYSTEM}/calib \
                     platform/base/sx



C_SRC := drv_pasw.c
S_SRC :=


## --------------Don't change the line below------------------ ##
include ${SOFT_WORKDIR}/env/compilation/compilerules.mk
