/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#include "cs_types.h"

//#include "mdi_m.h"

#include "hal_map_engine.h"

#include "mdi_map.h"


//# define HAL_MAP_ID_MDI HAL_MAP_ID_AUD
// =============================================================================
//  MACROS
// =============================================================================

#define MDI_BEIJING_VERSION_STRING "MDI module in branch of Total_integration"
#include "mdip_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_mdiMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_mdiMapVersion = MDI_VERSION_STRUCT;



// =============================================================================
// g_mdiMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED MDI_MAP_ACCESS_T g_mdiMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// mdi_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID mdi_RegisterYourself(VOID)
{
    g_mdiMapVersion.string=MDI_BEIJING_VERSION_STRING;
    hal_MapEngineRegisterModule(HAL_MAP_ID_MDI, &g_mdiMapVersion, &g_mdiMapAccess);
}
