#!/usr/bin/ruby
# Workspace management Helper tool.
# See WORKSPACE::WorkspaceHelper for documentation
# or run with help parameter.

#dependencies
# add /env/deliv/ to the ruby search path
$:.unshift(ENV['SOFT_WORKDIR']+'/env/deliv/')
require 'workspacelib.rb'

WORKSPACE::main

