/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Oct 24 20:47:17 2017. */

#ifndef PB_AT_SETTING_PB_H_INCLUDED
#define PB_AT_SETTING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _PB_AtSetting_AtTcpipSetting {
    uint32_t cipSCONT_unSaved;
    uint32_t cipMux_multiIp;
    uint32_t cipHEAD_addIpHead;
    uint32_t cipSHOWTP_dispTP;
    uint32_t cipSRIP_showIPPort;
    uint32_t cipATS_setTimer;
    uint32_t cipATS_time;
    uint32_t cipSPRT_sendPrompt;
    uint32_t cipQSEND_quickSend;
    uint32_t cipMODE_transParent;
    uint32_t cipCCFG_NmRetry;
    uint32_t cipCCFG_WaitTm;
    uint32_t cipCCFG_SendSz;
    uint32_t cipCCFG_esc;
    uint32_t cipCCFG_Rxmode;
    uint32_t cipCCFG_RxSize;
    uint32_t cipCCFG_Rxtimer;
    uint32_t cipDPDP_detectPDP;
    uint32_t cipDPDP_interval;
    uint32_t cipDPDP_timer;
    uint32_t cipCSGP_setGprs;
    uint32_t cipRDTIMER_rdsigtimer;
    uint32_t cipRDTIMER_rdmuxtimer;
    uint32_t cipRXGET_manualy;
    pb_callback_t cipApn;
    pb_callback_t cipUserName;
    pb_callback_t cipPassWord;
/* @@protoc_insertion_point(struct:PB_AtSetting_AtTcpipSetting) */
} PB_AtSetting_AtTcpipSetting;

typedef struct _PB_AtSetting_PB_CfgInfo {
    uint32_t ind_ctrl_mask;
    uint32_t sind_ctrl_mask;
    uint32_t te_chset;
    uint32_t mt_chset;
/* @@protoc_insertion_point(struct:PB_AtSetting_PB_CfgInfo) */
} PB_AtSetting_PB_CfgInfo;

typedef struct _PB_AtSmsSetting {
    uint32_t csmpFo;
    uint32_t csdhShow;
    pb_callback_t smsInfo;
    uint32_t smsFormat;
/* @@protoc_insertion_point(struct:PB_AtSmsSetting) */
} PB_AtSmsSetting;

typedef struct _PB_AtSmsSetting_AtSmsInfo_AtCnMi {
    uint32_t nMode;
    uint32_t nMt;
    uint32_t nBm;
    uint32_t nDs;
    uint32_t nBfr;
/* @@protoc_insertion_point(struct:PB_AtSmsSetting_AtSmsInfo_AtCnMi) */
} PB_AtSmsSetting_AtSmsInfo_AtCnMi;

typedef struct _PB_AtSetting {
    uint32_t resultCodePresent;
    uint32_t resultCodeFormat;
    uint32_t commandEchoMode;
    uint32_t nS3;
    uint32_t nS4;
    uint32_t nS5;
    uint32_t cmee;
    uint32_t cgreg;
    uint32_t crc;
    uint32_t rxfc;
    uint32_t txfc;
    uint32_t icfFormat;
    uint32_t icfParity;
    uint32_t dtrData;
    pb_callback_t cmerInd;
    PB_AtSetting_PB_CfgInfo cfgInfo;
    uint32_t cc_VTD;
    uint32_t cc_s0;
    uint32_t gprsAuto;
    uint32_t baudRate;
    pb_callback_t operFormat;
    uint32_t copsModeTemp;
    uint32_t preferredOperFormat;
    pb_callback_t preferredOperator;
    uint32_t preferredOperatorIndex;
    uint32_t preferredOperatorCaller;
    uint32_t pbkListEntryCaller;
    uint32_t pbkCharacterSet;
    uint32_t tempStorage;
    uint32_t alphabet;
    PB_AtSmsSetting smsSetting;
    uint32_t callWaitingPresentResultCode;
    uint32_t ussd;
    uint32_t ucClip;
    uint32_t ucClir;
    uint32_t ucColp;
    uint32_t ucCSSU;
    uint32_t ucCSSI;
    uint32_t moniPara;
    uint32_t monpPara;
    uint32_t pmIndMark;
    uint32_t vgrVolume;
    uint32_t vgtVolume;
    uint32_t cmutMute;
    uint32_t audioTestMode;
    PB_AtSetting_AtTcpipSetting tcpip;
    uint32_t secUartEnable;
    uint32_t secUartBaud;
    uint32_t secUartIcfFormat;
    uint32_t secUartIcfParity;
/* @@protoc_insertion_point(struct:PB_AtSetting) */
} PB_AtSetting;

typedef struct _PB_AtSmsSetting_AtSmsInfo {
    PB_AtSmsSetting_AtSmsInfo_AtCnMi sCnmi;
    uint32_t nStorage1;
    uint32_t nStorage2;
    uint32_t nStorage3;
    uint32_t nTotal1;
    uint32_t nTotal2;
    uint32_t nTotal3;
    uint32_t nUsed1;
    uint32_t nUsed2;
    uint32_t nUsed3;
    uint32_t nServType;
    uint32_t nOverflowCtrl;
    uint32_t nOverflowMode;
/* @@protoc_insertion_point(struct:PB_AtSmsSetting_AtSmsInfo) */
} PB_AtSmsSetting_AtSmsInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PB_AtSmsSetting_init_default             {0, 0, {{NULL}, NULL}, 0}
#define PB_AtSmsSetting_AtSmsInfo_init_default   {PB_AtSmsSetting_AtSmsInfo_AtCnMi_init_default, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_init_default {0, 0, 0, 0, 0}
#define PB_AtSetting_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, PB_AtSetting_PB_CfgInfo_init_default, 0, 0, 0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, PB_AtSmsSetting_init_default, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, PB_AtSetting_AtTcpipSetting_init_default, 0, 0, 0, 0}
#define PB_AtSetting_PB_CfgInfo_init_default     {0, 0, 0, 0}
#define PB_AtSetting_AtTcpipSetting_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PB_AtSmsSetting_init_zero                {0, 0, {{NULL}, NULL}, 0}
#define PB_AtSmsSetting_AtSmsInfo_init_zero      {PB_AtSmsSetting_AtSmsInfo_AtCnMi_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_init_zero {0, 0, 0, 0, 0}
#define PB_AtSetting_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, PB_AtSetting_PB_CfgInfo_init_zero, 0, 0, 0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, PB_AtSmsSetting_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, PB_AtSetting_AtTcpipSetting_init_zero, 0, 0, 0, 0}
#define PB_AtSetting_PB_CfgInfo_init_zero        {0, 0, 0, 0}
#define PB_AtSetting_AtTcpipSetting_init_zero    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define PB_AtSetting_AtTcpipSetting_cipSCONT_unSaved_tag 5
#define PB_AtSetting_AtTcpipSetting_cipMux_multiIp_tag 6
#define PB_AtSetting_AtTcpipSetting_cipHEAD_addIpHead_tag 7
#define PB_AtSetting_AtTcpipSetting_cipSHOWTP_dispTP_tag 8
#define PB_AtSetting_AtTcpipSetting_cipSRIP_showIPPort_tag 9
#define PB_AtSetting_AtTcpipSetting_cipATS_setTimer_tag 10
#define PB_AtSetting_AtTcpipSetting_cipATS_time_tag 11
#define PB_AtSetting_AtTcpipSetting_cipSPRT_sendPrompt_tag 12
#define PB_AtSetting_AtTcpipSetting_cipQSEND_quickSend_tag 13
#define PB_AtSetting_AtTcpipSetting_cipMODE_transParent_tag 14
#define PB_AtSetting_AtTcpipSetting_cipCCFG_NmRetry_tag 15
#define PB_AtSetting_AtTcpipSetting_cipCCFG_WaitTm_tag 16
#define PB_AtSetting_AtTcpipSetting_cipCCFG_SendSz_tag 17
#define PB_AtSetting_AtTcpipSetting_cipCCFG_esc_tag 18
#define PB_AtSetting_AtTcpipSetting_cipCCFG_Rxmode_tag 19
#define PB_AtSetting_AtTcpipSetting_cipCCFG_RxSize_tag 20
#define PB_AtSetting_AtTcpipSetting_cipCCFG_Rxtimer_tag 21
#define PB_AtSetting_AtTcpipSetting_cipDPDP_detectPDP_tag 22
#define PB_AtSetting_AtTcpipSetting_cipDPDP_interval_tag 23
#define PB_AtSetting_AtTcpipSetting_cipDPDP_timer_tag 24
#define PB_AtSetting_AtTcpipSetting_cipCSGP_setGprs_tag 25
#define PB_AtSetting_AtTcpipSetting_cipRDTIMER_rdsigtimer_tag 26
#define PB_AtSetting_AtTcpipSetting_cipRDTIMER_rdmuxtimer_tag 27
#define PB_AtSetting_AtTcpipSetting_cipRXGET_manualy_tag 28
#define PB_AtSetting_AtTcpipSetting_cipApn_tag   29
#define PB_AtSetting_AtTcpipSetting_cipUserName_tag 30
#define PB_AtSetting_AtTcpipSetting_cipPassWord_tag 31
#define PB_AtSetting_PB_CfgInfo_ind_ctrl_mask_tag 1
#define PB_AtSetting_PB_CfgInfo_sind_ctrl_mask_tag 2
#define PB_AtSetting_PB_CfgInfo_te_chset_tag     3
#define PB_AtSetting_PB_CfgInfo_mt_chset_tag     4
#define PB_AtSmsSetting_csmpFo_tag               1
#define PB_AtSmsSetting_csdhShow_tag             2
#define PB_AtSmsSetting_smsInfo_tag              3
#define PB_AtSmsSetting_smsFormat_tag            4
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_nMode_tag 1
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_nMt_tag 2
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_nBm_tag 3
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_nDs_tag 4
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_nBfr_tag 5
#define PB_AtSetting_resultCodePresent_tag       1
#define PB_AtSetting_resultCodeFormat_tag        2
#define PB_AtSetting_commandEchoMode_tag         3
#define PB_AtSetting_nS3_tag                     4
#define PB_AtSetting_nS4_tag                     5
#define PB_AtSetting_nS5_tag                     6
#define PB_AtSetting_cmee_tag                    7
#define PB_AtSetting_cgreg_tag                   8
#define PB_AtSetting_crc_tag                     9
#define PB_AtSetting_rxfc_tag                    10
#define PB_AtSetting_txfc_tag                    11
#define PB_AtSetting_icfFormat_tag               12
#define PB_AtSetting_icfParity_tag               13
#define PB_AtSetting_dtrData_tag                 14
#define PB_AtSetting_secUartEnable_tag           47
#define PB_AtSetting_secUartBaud_tag             48
#define PB_AtSetting_secUartIcfFormat_tag        49
#define PB_AtSetting_secUartIcfParity_tag        50
#define PB_AtSetting_cmerInd_tag                 15
#define PB_AtSetting_cfgInfo_tag                 16
#define PB_AtSetting_cc_VTD_tag                  17
#define PB_AtSetting_cc_s0_tag                   18
#define PB_AtSetting_gprsAuto_tag                19
#define PB_AtSetting_baudRate_tag                20
#define PB_AtSetting_operFormat_tag              21
#define PB_AtSetting_copsModeTemp_tag            22
#define PB_AtSetting_preferredOperFormat_tag     23
#define PB_AtSetting_preferredOperator_tag       24
#define PB_AtSetting_preferredOperatorIndex_tag  25
#define PB_AtSetting_preferredOperatorCaller_tag 26
#define PB_AtSetting_pbkListEntryCaller_tag      27
#define PB_AtSetting_pbkCharacterSet_tag         28
#define PB_AtSetting_tempStorage_tag             29
#define PB_AtSetting_alphabet_tag                30
#define PB_AtSetting_smsSetting_tag              31
#define PB_AtSetting_callWaitingPresentResultCode_tag 32
#define PB_AtSetting_ussd_tag                    33
#define PB_AtSetting_ucClip_tag                  34
#define PB_AtSetting_ucClir_tag                  35
#define PB_AtSetting_ucColp_tag                  36
#define PB_AtSetting_ucCSSU_tag                  37
#define PB_AtSetting_ucCSSI_tag                  38
#define PB_AtSetting_moniPara_tag                39
#define PB_AtSetting_monpPara_tag                40
#define PB_AtSetting_pmIndMark_tag               41
#define PB_AtSetting_vgrVolume_tag               42
#define PB_AtSetting_vgtVolume_tag               43
#define PB_AtSetting_cmutMute_tag                44
#define PB_AtSetting_audioTestMode_tag           45
#define PB_AtSetting_tcpip_tag                   46
#define PB_AtSmsSetting_AtSmsInfo_sCnmi_tag      1
#define PB_AtSmsSetting_AtSmsInfo_nStorage1_tag  2
#define PB_AtSmsSetting_AtSmsInfo_nStorage2_tag  3
#define PB_AtSmsSetting_AtSmsInfo_nStorage3_tag  4
#define PB_AtSmsSetting_AtSmsInfo_nTotal1_tag    5
#define PB_AtSmsSetting_AtSmsInfo_nTotal2_tag    6
#define PB_AtSmsSetting_AtSmsInfo_nTotal3_tag    7
#define PB_AtSmsSetting_AtSmsInfo_nUsed1_tag     8
#define PB_AtSmsSetting_AtSmsInfo_nUsed2_tag     9
#define PB_AtSmsSetting_AtSmsInfo_nUsed3_tag     10
#define PB_AtSmsSetting_AtSmsInfo_nServType_tag  11
#define PB_AtSmsSetting_AtSmsInfo_nOverflowCtrl_tag 12
#define PB_AtSmsSetting_AtSmsInfo_nOverflowMode_tag 13

/* Struct field encoding specification for nanopb */
extern const pb_field_t PB_AtSmsSetting_fields[5];
extern const pb_field_t PB_AtSmsSetting_AtSmsInfo_fields[14];
extern const pb_field_t PB_AtSmsSetting_AtSmsInfo_AtCnMi_fields[6];
extern const pb_field_t PB_AtSetting_fields[51];
extern const pb_field_t PB_AtSetting_PB_CfgInfo_fields[5];
extern const pb_field_t PB_AtSetting_AtTcpipSetting_fields[28];

/* Maximum encoded size of messages (where known) */
/* PB_AtSmsSetting_size depends on runtime parameters */
#define PB_AtSmsSetting_AtSmsInfo_size           104
#define PB_AtSmsSetting_AtSmsInfo_AtCnMi_size    30
/* PB_AtSetting_size depends on runtime parameters */
#define PB_AtSetting_PB_CfgInfo_size             24
/* PB_AtSetting_AtTcpipSetting_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define AT_SETTING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
